# Ansible playbook to install OSM nomiatim maps
# in local Ubuntu 16.04 vagrant box.
#
# This is the map install which requires an already
# running nominatim server/database.
# Following loosely:
#
#   https://github.com/twain47/Nominatim/blob/master/docs/Import_and_update.md
#
# The set of countries to install is set in var `countries` below.
# It must be available at http://download.geofabrik.de/europe/.
#
---
- hosts: all
  become: yes
  remote_user: root
  vars:
    username: "{{ ansible_ssh_user }}"
    userhome: "/home/{{ username }}"
    # the countries and their continent must exist on download.geofabrik.de
    countries:
        monaco:
            continent: "europe"
        andorra:
            continent: "europe"
  tasks:
  - name: Update cache if not done in last 24 hours.
    apt: update_cache=yes cache_valid_time=86400

  - name: Install system packages
    package:
      name={{ item }}
      state=present
    with_items:
      - aptitude

  - name: Aptitude safe-upgrade
    apt: upgrade=safe

  - name: Create data/ dir
    become: no
    file:
      path: /home/vagrant/data
      state: directory

  - name: Download map data for [{{ item.key }}]
    become: no
    get_url:
      url: "http://download.geofabrik.de/{{ item.value.continent }}/{{ item.key }}-latest.osm.pbf"
      dest: "{{ userhome }}/data/{{ item.key }}.osm.pbf"
    with_dict: "{{ countries }}"

  - name: Remove old data
    become: no
    shell: dropdb --if-exists nominatim

  - name: Setup ["{{ item.key }}"]
    become: no
    shell: ./utils/setup.php --osm-file "../data/{{ item.key }}.osm.pbf" --osm2pgsql-cache 1000 --all 2>&1 | tee "{{ item.key }}.$$.log"
    args:
      chdir: /home/vagrant/build
    with_dict: "{{ countries }}"

  - name: Build special phrases
    become: no
    shell: ./utils/specialphrases.php --wiki-import > ../data/specialphrases.sql
    args:
      chdir: /home/vagrant/build
      creates: /home/vagrant/data/specialphrases.sql

  - name: Process SQL
    become: no
    shell: psql -d nominatim -f ../data/specialphrases.sql
    args:
      chdir: /home/vagrant/build
