# Ansible playbook to install OSM nomiatim server
# in local Ubuntu 16.04 vagrant box.
#
# This is the basic install (no real map data (yet))
# Following loosely:
#
#   https://github.com/twain47/Nominatim/blob/master/docs/install-on-ubuntu-16.md
#
---
- hosts: all
  become: yes
  remote_user: root
  tasks:
  - name: Update package cache if not done in last 24 hours.
    apt: update_cache=yes cache_valid_time=86400

  - name: Install system packages
    package:
      name={{ item }}
      state=present
    with_items:
      - aptitude

  - name: Aptitude safe-upgrade
    apt: upgrade=safe

  - name: Install all packages needed for Nominatim
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - build-essential
      - cmake
      - g++
      - libboost-dev
      - libboost-system-dev
      - libboost-filesystem-dev
      - libexpat1-dev
      - zlib1g-dev
      - libxml2-dev
      - libbz2-dev
      - libpq-dev
      - libgeos-dev
      - libgeos++-dev
      - libproj-dev
      - postgresql-server-dev-9.5
      - postgresql-9.5-postgis-2.2
      - postgresql-contrib-9.5
      - apache2
      - php
      - php-pgsql
      - libapache2-mod-php
      - php-pear
      - php-db
      - git
