# Ansible playbook to install OSM nomiatim server
# in local Ubuntu 16.04 vagrant box.
#
# This is the basic install (no real map data (yet))
# Following loosely:
#
#   https://github.com/twain47/Nominatim/blob/master/docs/install-on-ubuntu-16.md
#
# This script requires an existent user on the target system. You can set the
# user and userhome below.
#
---
- hosts: all
  #  Do not set this to "yes". This would break `username` determination below.
  become: no
  vars:
    # do you want test packages installed (additionally)?
    install_test_packages: false
    # username to install nominatim as
    username: "{{ ansible_ssh_user }}"
    userhome: "/home/{{ username }}"
  tasks:
  - name: Update package cache if not done in last 24 hours.
    apt: update_cache=yes cache_valid_time=86400
    become: yes

  - name: Install system packages
    package:
      name={{ item }}
      state=present
    become: yes
    with_items:
      - aptitude

  - name: Aptitude safe-upgrade
    apt: upgrade=safe
    become: yes

  - name: Install all packages needed for Nominatim
    apt:
      name: "{{ item }}"
      state: present
    become: yes
    with_items:
      - build-essential
      - cmake
      - g++
      - libboost-dev
      - libboost-system-dev
      - libboost-filesystem-dev
      - libexpat1-dev
      - zlib1g-dev
      - libxml2-dev
      - libbz2-dev
      - libpq-dev
      - libgeos-dev
      - libgeos++-dev
      - libproj-dev
      - postgresql-server-dev-9.5
      - postgresql-9.5-postgis-2.2
      - postgresql-contrib-9.5
      - apache2
      - php
      - php-pgsql
      - libapache2-mod-php
      - php-pear
      - php-db
      - git
      - python-psycopg2

  - name: Install additional packages to run the test suite
    apt:
      name: "{{ item }}"
      state: present
    become: yes
    when: install_test_packages
    with_items:
      - python-dev
      - python-pip
      - python-levenshtein
      - python-shapely
      - tidy
      - python-nose
      - python-tidylib
      - python-numpy
      - phpunit

  - name: Install additional python packages to run test suite
    become: no
    pip:
      name: "{{ item }}"
      state: present
      extra_args: "--user"
    with_items:
      - "lettuce==0.2.18"
      - "six==1.7"
      - "haversine"
    when: install_test_packages

  - name: Install php codesniffer if test_suite is wanted
    pear:
      name: PHP_CodeSniffer
      state: present
    become: yes
    when: install_test_packages

  - name: Restart postgres
    become: yes
    service:
      name: postgresql
      state: restarted

  - name: Create postgres user {{ username }}
    become: yes
    become_user: postgres
    postgresql_user:
      name: "{{ username }}"
      role_attr_flags: SUPERUSER
      state: present

  - name: Copy over apache config
    become: yes
    template:
      src: apache_nominatim.conf
      dest: /etc/apache2/conf-available/nominatim.conf
      owner: root

  - name: Enable new apache config
    become: yes
    shell: /usr/sbin/a2enconf nominatim
    args:
      creates: /etc/apache2/conf-enabled/nominatim.conf

  - name: Clone nominatim from github
    git:
      repo: git://github.com/twain47/Nominatim.git
      dest: "{{ userhome }}/Nominatim"
      update: yes
